[package]
name = "ristretto-encode"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

[dependencies]
curve25519-dalek = "3"

[dev-dependencies]
rand = "0.8"
